from decouple import config

# MongoDB Connection
MONGO_DETAILS = config("MONGO_DETAILS")
DATABASE_NAME= config("DATABASE_NAME")
USER_COLLECTION = config("USER_COLLECTION")
PLACE_COLLECTION = config("PLACE_COLLECTION")

# APIs
GOOGLE_API_KEY = config("GOOGLE_API_KEY") 
OPEN_WEATHER_API_KEY = config("OPEN_WEATHER_API_KEY") 
GOOGLE_PLACES_API_KEY = config("GOOGLE_PLACES_API_KEY")
GEMINI_MODEL_NAME = config("GEMINI_MODEL_NAME")